# Generated by Django 4.2.11 on 2025-07-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('imageURL', models.CharField(max_length=200, null=True)),
                ('ammount', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(choices=[('ALIMENTO', 'Alimento'), ('BRINQUEDO', 'Brinquedo'), ('PERFUME', 'Perfume'), ('ROUPA', 'Roupa'), ('OUTRO', 'Outro')], max_length=10)),
            ],
        ),
    ]
