# Generated by Django 4.2.11 on 2025-07-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageURL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
