# Generated by Django 4.2.11 on 2025-07-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ammount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
