# Generated by Django 4.2.11 on 2025-07-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], default='MASCULINO', max_length=10),
            preserve_default=False,
        ),
    ]
