# Generated by Django 4.2.11 on 2025-07-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_appointment_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(default='2025-01-01 12:00', unique=True),
            preserve_default=False,
        ),
    ]
